"""add vk_id to user

Revision ID: 296fad1e2c65
Revises: 197ca095088c
Create Date: 2026-07-22 18:32:22.052871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296fad1e2c65'
down_revision: Union[str, Sequence[str], None] = '197ca095088c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vk_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vk_id')
    # ### end Alembic commands ###
